# Benchmark configuration for Poetry Slam
# Uses the opponent diversity first strategy for model selection

# Core benchmark settings
benchmark:
  id: "poetry_slam_benchmark_1"                # Unique identifier for this benchmark
  base_config: "config/games/poetry_slam.yaml" # Base game configuration
  type: "multi_player"                         # Multi-player tournament
  sessions: 10                                 # Number of tournament sessions to run
  output_dir: "data/benchmark"                 # Directory for benchmark results
  players_per_game: 7                          # Number of players per game

  # Role definitions with relationships
  roles:
    author:
      count: 7  # All players are authors
      selection: "random"
    prompter:
      count: 1
      selection: "weighted_inverse"
      inherits: ["author"]  # Prompter is also an author

# Models to benchmark
models:
  - deepseek:deepseek-chat
  - deepseek:deepseek-reasoner
  - openai:gpt-4o
  - openai:gpt-4.5-preview
  - anthropic:claude-3-5-sonnet-20240620
  - anthropic:claude-3-7-sonnet-20250219
  - xai:grok-2-1212
  - mistral:mistral-large-latest
  - google:gemini-2.0-flash
  - google:gemini-2.0-flash-thinking-exp-01-21