# config/games/prisoners_dilemma.yaml
game:
  name: "Prisoner's Dilemma"
  description: "A classic game of cooperation and betrayal"
  type: "simultaneous_choice"

players:
  min: 2
  max: 2
  roles: "symmetric"

setup:
  initial_state:
    resources: []
    assignments: []

phases:
  - id: "decision"
    type: "simultaneous_action"
    actions:
      - name: "choose"
        options: ["cooperate", "defect"]
    next_phase: "resolution"

  - id: "resolution"
    type: "automatic"
    handler: "calculate_pd_outcome"
    next_phase_condition: "rounds_remaining"
    next_phase_success: "decision"  # If more rounds remain
    next_phase_failure: "game_end"  # If all rounds complete

rounds:
  count: 5
  progression: "fixed"

state:
  player_state:
    - name: "score"
      initial: 0
      visible: true
  shared_state:
    - name: "current_round"
      initial: 1
      visible: true
  hidden_state: []
  history_state:
    - name: "decision_history"
      tracking: "decisions"

win_condition:
  type: "highest_score"
  score_field: "score"
  trigger: "rounds_complete"

scoring:
  rules:
    - condition: "both_cooperate"
      points: [3, 3]
    - condition: "both_defect"
      points: [1, 1]
    - condition: "p1_defect_p2_cooperate"
      points: [5, 0]
    - condition: "p1_cooperate_p2_defect"
      points: [0, 5]

llm_integration:
  player_models:
    player_1: "openai:gpt-4o"
    player_2: "anthropic:claude-3-5-sonnet-20240620"
  system_prompts:
    decision: |
      Your role is a player in a Prisoner's Dilemma game.
      You must decide whether to cooperate with or defect against your opponent.
      The payoffs are:
      - If both players cooperate: 3 points each
      - If both players defect: 1 point each
      - If you defect and they cooperate: You get 5 points, they get 0
      - If you cooperate and they defect: You get 0 points, they get 5"

      Think strategically about cooperation and self-interest.
      Your goal is to win the game by having a higher score than your opponent after the final round.
      Please respond as the player directly, not as an advisor.
      Feel free to think out loud about the problem a bit before making a decision, but keep it relatively short.
      Once you have a decision, put that decision inside double brackets, like this: [[COOPERATE]] or [[DEFECT]].
      If your response does not contain a decision formatted with double brackets, you will be disqualified and lose the game.
  prompts:
    decision: "pd_decision"
  parsers:
    decision: "choice_parser"